name: fcaihu
description: app for fcai-hu

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+3
  cupertino_icons: ^0.1.3
  introduction_screen: ^1.0.7
  flare_splash_screen: ^3.0.1
  cached_network_image: ^2.0.0
  flare_flutter:
  http:
  intl: ^0.16.1
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.4
  uuid:
  path_provider:
  firebase_storage:
  image_picker:
  firebase_core:
  flutter_image_compress: ^0.6.5+1
  provider:
  firebase_messaging:
  flutter_full_pdf_viewer: ^1.0.6
  youtube_player_flutter:
  flutter_slidable: ^0.5.4
  connectivity: ^0.4.8+2
  carousel_slider: 1.4.1
  flutter_signin_button: ^0.2.8
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/welcome/
    - assets/images/
    - assets/slider/
    - assets/second_splash_screen_animation.flr
    - assets/sign_In_animation.flr
    - assets/welcome_animation.flr
    - assets/loading_animation_white.flr
    - assets/loading_animation_purple.flr
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
